# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e39452361766811b10d37ed12915ee5aeb48a761b4ca47130717b11e299104710f881ba485eb2b2f287c7c62b67b7b98ec3af2591b27b9c8b9b6d4bfd4982607

test:
  secret_key_base: a8badd57c552a0b9d04e2601cd5c9bebf30e503752f1e3f2ac8d36b9730dc1330cc025e99df076398b1c759627d36d28b6d191dcf07438ecd7e05c251b7efd8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
